// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: domain/connection/connection.proto

package connection

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/superwhys/remoteX/internal/proto/ext"
	protocol "github.com/superwhys/remoteX/pkg/protocol"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Connection struct {
	ConnectionId  string                      `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connectionId" yaml:"-"`
	LocalAddress  string                      `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"localAddress" yaml:"-"`
	RemoteAddress string                      `protobuf:"bytes,3,opt,name=remote_address,json=remoteAddress,proto3" json:"remoteAddress" yaml:"-"`
	Protocol      protocol.ConnectionProtocol `protobuf:"varint,4,opt,name=protocol,proto3,enum=protocol.ConnectionProtocol" json:"protocol" yaml:"-"`
	ConnectType   protocol.ConnectionType     `protobuf:"varint,5,opt,name=connect_type,json=connectType,proto3,enum=protocol.ConnectionType" json:"connectType" yaml:"-"`
	Status        protocol.ConnectionStatus   `protobuf:"varint,6,opt,name=status,proto3,enum=protocol.ConnectionStatus" json:"status" yaml:"-"`
	StartTime     int64                       `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"startTime" yaml:"-"`
	LastHeartbeat int64                       `protobuf:"varint,8,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"lastHeartbeat" yaml:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c8286653a4531df, []int{0}
}
func (m *Connection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(m, src)
}
func (m *Connection) XXX_Size() int {
	return m.ProtoSize()
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *Connection) GetLocalAddress() string {
	if m != nil {
		return m.LocalAddress
	}
	return ""
}

func (m *Connection) GetRemoteAddress() string {
	if m != nil {
		return m.RemoteAddress
	}
	return ""
}

func (m *Connection) GetProtocol() protocol.ConnectionProtocol {
	if m != nil {
		return m.Protocol
	}
	return protocol.ConnectionProtocolTcp
}

func (m *Connection) GetConnectType() protocol.ConnectionType {
	if m != nil {
		return m.ConnectType
	}
	return protocol.ConnectionTypeServer
}

func (m *Connection) GetStatus() protocol.ConnectionStatus {
	if m != nil {
		return m.Status
	}
	return protocol.ConnectionStatusBeforeAuth
}

func (m *Connection) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Connection) GetLastHeartbeat() int64 {
	if m != nil {
		return m.LastHeartbeat
	}
	return 0
}

func init() {
	proto.RegisterType((*Connection)(nil), "connection.Connection")
}

func init() {
	proto.RegisterFile("domain/connection/connection.proto", fileDescriptor_7c8286653a4531df)
}

var fileDescriptor_7c8286653a4531df = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x31, 0x6f, 0x9b, 0x40,
	0x14, 0xc7, 0xa1, 0x76, 0x5d, 0xfb, 0x5a, 0x7b, 0x60, 0xa8, 0xae, 0xb6, 0x0b, 0x16, 0x93, 0x97,
	0x82, 0xd4, 0x2e, 0x55, 0x36, 0x93, 0x0c, 0x49, 0x94, 0x21, 0x72, 0x3c, 0x58, 0x59, 0xd0, 0x19,
	0x4e, 0x36, 0x0a, 0xf8, 0x10, 0x77, 0x56, 0xc2, 0xb7, 0xc8, 0x47, 0xc8, 0xc7, 0xc9, 0x68, 0x65,
	0xca, 0x84, 0x14, 0xb3, 0x31, 0xe6, 0x13, 0x44, 0x1c, 0x18, 0x7c, 0x8a, 0xb7, 0xa7, 0xff, 0xef,
	0xbd, 0x9f, 0x78, 0x8f, 0x03, 0xba, 0x4b, 0x02, 0xe4, 0xad, 0x4d, 0x87, 0xac, 0xd7, 0xd8, 0x61,
	0x1e, 0x39, 0x2c, 0x8d, 0x30, 0x22, 0x8c, 0x28, 0xa0, 0x4e, 0xfa, 0x1d, 0xfc, 0xc0, 0x8a, 0xb8,
	0x3f, 0x08, 0xef, 0x96, 0x26, 0x2f, 0x1d, 0xe2, 0x57, 0x45, 0x01, 0xf5, 0x97, 0x26, 0x00, 0xa7,
	0xd5, 0x98, 0x32, 0x01, 0xdd, 0x5a, 0x62, 0x7b, 0x2e, 0x94, 0x47, 0xf2, 0xb8, 0x63, 0x0d, 0xb3,
	0x44, 0xfb, 0x51, 0x83, 0x0b, 0xf7, 0x3d, 0xd1, 0xda, 0x31, 0x0a, 0xfc, 0x13, 0xfd, 0x8f, 0x3e,
	0x15, 0x48, 0xae, 0xf0, 0x89, 0x83, 0x7c, 0x1b, 0xb9, 0x6e, 0x84, 0x29, 0x85, 0x5f, 0x6a, 0x05,
	0x07, 0x93, 0x22, 0x17, 0x15, 0x87, 0x44, 0x39, 0x03, 0xbd, 0x08, 0x07, 0x84, 0xe1, 0xca, 0xd1,
	0xe0, 0x8e, 0xdf, 0x59, 0xa2, 0x75, 0x0b, 0x72, 0x4c, 0x22, 0x22, 0x65, 0x0a, 0xda, 0xfb, 0x65,
	0x61, 0x73, 0x24, 0x8f, 0x7b, 0x7f, 0x87, 0x46, 0xb5, 0x7d, 0xbd, 0xf3, 0x75, 0x19, 0x59, 0x30,
	0x4b, 0xb4, 0x6a, 0x42, 0x10, 0x57, 0xa9, 0x32, 0x07, 0xfb, 0x65, 0x6d, 0x16, 0x87, 0x18, 0x7e,
	0xe5, 0x5e, 0x78, 0xcc, 0x3b, 0x8b, 0x43, 0x6c, 0x0d, 0xb2, 0x44, 0xfb, 0x5e, 0x4e, 0xe4, 0x81,
	0xa0, 0x3d, 0x04, 0xca, 0x25, 0x68, 0x51, 0x86, 0xd8, 0x86, 0xc2, 0x16, 0x77, 0xf6, 0x8f, 0x39,
	0x6f, 0x78, 0x87, 0xf5, 0x33, 0x4b, 0xb4, 0xb2, 0x5b, 0x10, 0x96, 0x99, 0xf2, 0x1f, 0x00, 0xca,
	0x50, 0xc4, 0x6c, 0xe6, 0x05, 0x18, 0x7e, 0x1b, 0xc9, 0xe3, 0x86, 0xf5, 0x2b, 0x4b, 0xb4, 0x0e,
	0x4f, 0x67, 0x5e, 0x20, 0x7e, 0x47, 0x1d, 0xe7, 0x97, 0xf7, 0x11, 0x65, 0xf6, 0x0a, 0xa3, 0x88,
	0x2d, 0x30, 0x62, 0xb0, 0xcd, 0xa7, 0xf9, 0xe5, 0x73, 0x72, 0xbe, 0x07, 0xe2, 0xe5, 0x05, 0x64,
	0x5d, 0x6d, 0xdf, 0x54, 0xe9, 0x79, 0xa7, 0xca, 0xdb, 0x9d, 0x2a, 0x3f, 0xa6, 0xaa, 0xf4, 0x94,
	0xaa, 0xf2, 0x36, 0x55, 0xa5, 0xd7, 0x54, 0x95, 0x6e, 0x8d, 0xa5, 0xc7, 0x56, 0x9b, 0x85, 0xe1,
	0x90, 0xc0, 0xa4, 0x9b, 0x10, 0x47, 0xf7, 0xab, 0x98, 0x9a, 0xc5, 0xbf, 0x9b, 0x9b, 0x9f, 0xde,
	0xf9, 0xa2, 0xc5, 0x0f, 0xf1, 0xef, 0x23, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x77, 0x50, 0x05, 0x03,
	0x03, 0x00, 0x00,
}

func (m *Connection) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Connection) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Connection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastHeartbeat != 0 {
		i = encodeVarintConnection(dAtA, i, uint64(m.LastHeartbeat))
		i--
		dAtA[i] = 0x40
	}
	if m.StartTime != 0 {
		i = encodeVarintConnection(dAtA, i, uint64(m.StartTime))
		i--
		dAtA[i] = 0x38
	}
	if m.Status != 0 {
		i = encodeVarintConnection(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if m.ConnectType != 0 {
		i = encodeVarintConnection(dAtA, i, uint64(m.ConnectType))
		i--
		dAtA[i] = 0x28
	}
	if m.Protocol != 0 {
		i = encodeVarintConnection(dAtA, i, uint64(m.Protocol))
		i--
		dAtA[i] = 0x20
	}
	if len(m.RemoteAddress) > 0 {
		i -= len(m.RemoteAddress)
		copy(dAtA[i:], m.RemoteAddress)
		i = encodeVarintConnection(dAtA, i, uint64(len(m.RemoteAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.LocalAddress) > 0 {
		i -= len(m.LocalAddress)
		copy(dAtA[i:], m.LocalAddress)
		i = encodeVarintConnection(dAtA, i, uint64(len(m.LocalAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintConnection(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintConnection(dAtA []byte, offset int, v uint64) int {
	offset -= sovConnection(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Connection) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovConnection(uint64(l))
	}
	l = len(m.LocalAddress)
	if l > 0 {
		n += 1 + l + sovConnection(uint64(l))
	}
	l = len(m.RemoteAddress)
	if l > 0 {
		n += 1 + l + sovConnection(uint64(l))
	}
	if m.Protocol != 0 {
		n += 1 + sovConnection(uint64(m.Protocol))
	}
	if m.ConnectType != 0 {
		n += 1 + sovConnection(uint64(m.ConnectType))
	}
	if m.Status != 0 {
		n += 1 + sovConnection(uint64(m.Status))
	}
	if m.StartTime != 0 {
		n += 1 + sovConnection(uint64(m.StartTime))
	}
	if m.LastHeartbeat != 0 {
		n += 1 + sovConnection(uint64(m.LastHeartbeat))
	}
	return n
}

func sovConnection(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConnection(x uint64) (n int) {
	return sovConnection(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Connection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConnection
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Connection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Connection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConnection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConnection
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConnection
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocalAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConnection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConnection
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConnection
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LocalAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConnection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConnection
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConnection
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoteAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Protocol", wireType)
			}
			m.Protocol = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConnection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Protocol |= protocol.ConnectionProtocol(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectType", wireType)
			}
			m.ConnectType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConnection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConnectType |= protocol.ConnectionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConnection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= protocol.ConnectionStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			m.StartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConnection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastHeartbeat", wireType)
			}
			m.LastHeartbeat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConnection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastHeartbeat |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConnection(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConnection
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConnection(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConnection
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConnection
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConnection
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConnection
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConnection
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConnection
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConnection        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConnection          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConnection = fmt.Errorf("proto: unexpected end of group")
)
