// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal/filesync/pb/filesync.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/superwhys/remoteX/internal/proto/ext"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FileBase struct {
	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" yaml:"-"`
	Wpath   string `protobuf:"bytes,2,opt,name=wpath,proto3" json:"wpath" yaml:"-"`
	Regular bool   `protobuf:"varint,3,opt,name=regular,proto3" json:"regular" yaml:"-"`
	Size    int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size" yaml:"-"`
	IsEnd   bool   `protobuf:"varint,5,opt,name=is_end,json=isEnd,proto3" json:"isEnd" yaml:"-"`
}

func (m *FileBase) Reset()         { *m = FileBase{} }
func (m *FileBase) String() string { return proto.CompactTextString(m) }
func (*FileBase) ProtoMessage()    {}
func (*FileBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2a1b515271a6305, []int{0}
}
func (m *FileBase) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FileBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FileBase.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FileBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileBase.Merge(m, src)
}
func (m *FileBase) XXX_Size() int {
	return m.ProtoSize()
}
func (m *FileBase) XXX_DiscardUnknown() {
	xxx_messageInfo_FileBase.DiscardUnknown(m)
}

var xxx_messageInfo_FileBase proto.InternalMessageInfo

func (m *FileBase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileBase) GetWpath() string {
	if m != nil {
		return m.Wpath
	}
	return ""
}

func (m *FileBase) GetRegular() bool {
	if m != nil {
		return m.Regular
	}
	return false
}

func (m *FileBase) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileBase) GetIsEnd() bool {
	if m != nil {
		return m.IsEnd
	}
	return false
}

type FileList struct {
	TotalSize int64       `protobuf:"varint,1,opt,name=total_size,json=totalSize,proto3" json:"totalSize" yaml:"-"`
	Strip     string      `protobuf:"bytes,2,opt,name=strip,proto3" json:"strip" yaml:"-"`
	Files     []*FileBase `protobuf:"bytes,3,rep,name=files,proto3" json:"files" yaml:"-"`
}

func (m *FileList) Reset()         { *m = FileList{} }
func (m *FileList) String() string { return proto.CompactTextString(m) }
func (*FileList) ProtoMessage()    {}
func (*FileList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2a1b515271a6305, []int{1}
}
func (m *FileList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FileList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FileList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FileList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileList.Merge(m, src)
}
func (m *FileList) XXX_Size() int {
	return m.ProtoSize()
}
func (m *FileList) XXX_DiscardUnknown() {
	xxx_messageInfo_FileList.DiscardUnknown(m)
}

var xxx_messageInfo_FileList proto.InternalMessageInfo

func (m *FileList) GetTotalSize() int64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *FileList) GetStrip() string {
	if m != nil {
		return m.Strip
	}
	return ""
}

func (m *FileList) GetFiles() []*FileBase {
	if m != nil {
		return m.Files
	}
	return nil
}

type FileIdx struct {
	Idx int64 `protobuf:"varint,1,opt,name=idx,proto3" json:"idx" yaml:"-"`
}

func (m *FileIdx) Reset()         { *m = FileIdx{} }
func (m *FileIdx) String() string { return proto.CompactTextString(m) }
func (*FileIdx) ProtoMessage()    {}
func (*FileIdx) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2a1b515271a6305, []int{2}
}
func (m *FileIdx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FileIdx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FileIdx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FileIdx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileIdx.Merge(m, src)
}
func (m *FileIdx) XXX_Size() int {
	return m.ProtoSize()
}
func (m *FileIdx) XXX_DiscardUnknown() {
	xxx_messageInfo_FileIdx.DiscardUnknown(m)
}

var xxx_messageInfo_FileIdx proto.InternalMessageInfo

func (m *FileIdx) GetIdx() int64 {
	if m != nil {
		return m.Idx
	}
	return 0
}

type HashBuf struct {
	Offset int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset" yaml:"-"`
	Len    int64  `protobuf:"varint,2,opt,name=len,proto3" json:"len" yaml:"-"`
	Index  int64  `protobuf:"varint,3,opt,name=index,proto3" json:"index" yaml:"-"`
	Sum1   uint32 `protobuf:"varint,4,opt,name=sum1,proto3" json:"sum1" yaml:"-"`
	Sum2   []byte `protobuf:"bytes,5,opt,name=sum2,proto3" json:"sum2" yaml:"-"`
}

func (m *HashBuf) Reset()         { *m = HashBuf{} }
func (m *HashBuf) String() string { return proto.CompactTextString(m) }
func (*HashBuf) ProtoMessage()    {}
func (*HashBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2a1b515271a6305, []int{3}
}
func (m *HashBuf) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HashBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HashBuf.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HashBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashBuf.Merge(m, src)
}
func (m *HashBuf) XXX_Size() int {
	return m.ProtoSize()
}
func (m *HashBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_HashBuf.DiscardUnknown(m)
}

var xxx_messageInfo_HashBuf proto.InternalMessageInfo

func (m *HashBuf) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *HashBuf) GetLen() int64 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *HashBuf) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *HashBuf) GetSum1() uint32 {
	if m != nil {
		return m.Sum1
	}
	return 0
}

func (m *HashBuf) GetSum2() []byte {
	if m != nil {
		return m.Sum2
	}
	return nil
}

type HashHead struct {
	// number of blocks
	CheckSumCount int64 `protobuf:"varint,1,opt,name=check_sum_count,json=checkSumCount,proto3" json:"checkSumCount" yaml:"-"`
	// block length in the file
	BlockLength    int64 `protobuf:"varint,2,opt,name=block_length,json=blockLength,proto3" json:"blockLength" yaml:"-"`
	CheckSumLength int64 `protobuf:"varint,3,opt,name=check_sum_length,json=checkSumLength,proto3" json:"checkSumLength" yaml:"-"`
	// RemainderLength is fileLength % BlockLength
	RemainderLength int64      `protobuf:"varint,4,opt,name=remainder_length,json=remainderLength,proto3" json:"remainderLength" yaml:"-"`
	Hashs           []*HashBuf `protobuf:"bytes,5,rep,name=hashs,proto3" json:"hashs" yaml:"-"`
}

func (m *HashHead) Reset()         { *m = HashHead{} }
func (m *HashHead) String() string { return proto.CompactTextString(m) }
func (*HashHead) ProtoMessage()    {}
func (*HashHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2a1b515271a6305, []int{4}
}
func (m *HashHead) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HashHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HashHead.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HashHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashHead.Merge(m, src)
}
func (m *HashHead) XXX_Size() int {
	return m.ProtoSize()
}
func (m *HashHead) XXX_DiscardUnknown() {
	xxx_messageInfo_HashHead.DiscardUnknown(m)
}

var xxx_messageInfo_HashHead proto.InternalMessageInfo

func (m *HashHead) GetCheckSumCount() int64 {
	if m != nil {
		return m.CheckSumCount
	}
	return 0
}

func (m *HashHead) GetBlockLength() int64 {
	if m != nil {
		return m.BlockLength
	}
	return 0
}

func (m *HashHead) GetCheckSumLength() int64 {
	if m != nil {
		return m.CheckSumLength
	}
	return 0
}

func (m *HashHead) GetRemainderLength() int64 {
	if m != nil {
		return m.RemainderLength
	}
	return 0
}

func (m *HashHead) GetHashs() []*HashBuf {
	if m != nil {
		return m.Hashs
	}
	return nil
}

type FileChunk struct {
	Hash  *HashBuf `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash" yaml:"-"`
	Data  []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data" yaml:"-"`
	IsEnd bool     `protobuf:"varint,3,opt,name=is_end,json=isEnd,proto3" json:"isEnd" yaml:"-"`
}

func (m *FileChunk) Reset()         { *m = FileChunk{} }
func (m *FileChunk) String() string { return proto.CompactTextString(m) }
func (*FileChunk) ProtoMessage()    {}
func (*FileChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2a1b515271a6305, []int{5}
}
func (m *FileChunk) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FileChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FileChunk.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FileChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChunk.Merge(m, src)
}
func (m *FileChunk) XXX_Size() int {
	return m.ProtoSize()
}
func (m *FileChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChunk.DiscardUnknown(m)
}

var xxx_messageInfo_FileChunk proto.InternalMessageInfo

func (m *FileChunk) GetHash() *HashBuf {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *FileChunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *FileChunk) GetIsEnd() bool {
	if m != nil {
		return m.IsEnd
	}
	return false
}

func init() {
	proto.RegisterType((*FileBase)(nil), "pb.FileBase")
	proto.RegisterType((*FileList)(nil), "pb.FileList")
	proto.RegisterType((*FileIdx)(nil), "pb.FileIdx")
	proto.RegisterType((*HashBuf)(nil), "pb.HashBuf")
	proto.RegisterType((*HashHead)(nil), "pb.HashHead")
	proto.RegisterType((*FileChunk)(nil), "pb.FileChunk")
}

func init() {
	proto.RegisterFile("internal/filesync/pb/filesync.proto", fileDescriptor_e2a1b515271a6305)
}

var fileDescriptor_e2a1b515271a6305 = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x4b, 0x6e, 0xd3, 0x40,
	0x18, 0x80, 0xe3, 0xba, 0x69, 0x93, 0x69, 0x4b, 0xab, 0xe1, 0x65, 0x1e, 0xf5, 0x44, 0x06, 0xa4,
	0x48, 0x40, 0x42, 0xc2, 0x06, 0x21, 0x81, 0xc0, 0x55, 0x51, 0x41, 0x95, 0x90, 0xda, 0x0d, 0x62,
	0x13, 0x4d, 0xe2, 0x49, 0x6d, 0xd5, 0x1e, 0x5b, 0x1e, 0x5b, 0x4d, 0x39, 0x05, 0x47, 0xa8, 0x38,
	0x03, 0x87, 0xe8, 0x32, 0x4b, 0x56, 0x96, 0xda, 0xac, 0xb0, 0x58, 0x71, 0x02, 0x34, 0xbf, 0x27,
	0x6d, 0x9c, 0x56, 0x62, 0xe7, 0xff, 0xfb, 0xdf, 0x8f, 0x31, 0x7a, 0xe4, 0xf1, 0x84, 0xc5, 0x9c,
	0xfa, 0xed, 0xa1, 0xe7, 0x33, 0x71, 0xcc, 0x07, 0xed, 0xa8, 0x7f, 0xf1, 0xdd, 0x8a, 0xe2, 0x30,
	0x09, 0xf1, 0x42, 0xd4, 0xbf, 0x5f, 0x67, 0xa3, 0xa4, 0x10, 0xad, 0x3f, 0x1a, 0xaa, 0x7d, 0xf0,
	0x7c, 0x66, 0x53, 0xc1, 0x70, 0x13, 0x2d, 0x72, 0x1a, 0x30, 0x43, 0x6b, 0x68, 0xcd, 0xba, 0x7d,
	0x2b, 0xcf, 0x08, 0xc8, 0x7f, 0x33, 0x52, 0x3b, 0xa6, 0x81, 0xff, 0xda, 0x7a, 0x6e, 0xed, 0x01,
	0xc1, 0x4f, 0x51, 0xf5, 0x28, 0xa2, 0x89, 0x6b, 0x2c, 0x80, 0xe9, 0xed, 0x3c, 0x23, 0x05, 0x28,
	0xd9, 0x16, 0x08, 0x77, 0xd0, 0x72, 0xcc, 0x0e, 0x52, 0x9f, 0xc6, 0x86, 0xde, 0xd0, 0x9a, 0x35,
	0xfb, 0x6e, 0x9e, 0x91, 0x29, 0x2a, 0x39, 0x4c, 0xa1, 0xac, 0x44, 0x78, 0xdf, 0x98, 0xb1, 0xd8,
	0xd0, 0x9a, 0x7a, 0x51, 0x89, 0x94, 0xcb, 0x95, 0x48, 0x82, 0x9f, 0xa1, 0x25, 0x4f, 0xf4, 0x18,
	0x77, 0x8c, 0x2a, 0xc4, 0x86, 0x52, 0x3c, 0xb1, 0xcd, 0x9d, 0x72, 0x29, 0x80, 0xac, 0x9f, 0xaa,
	0xdd, 0x5d, 0x4f, 0x24, 0xf8, 0x15, 0x42, 0x49, 0x98, 0x50, 0xbf, 0x07, 0xa9, 0x34, 0x48, 0x75,
	0x2f, 0xcf, 0x48, 0x1d, 0xe8, 0xfe, 0x7c, 0xbe, 0x4b, 0x2c, 0xdb, 0x17, 0x49, 0xec, 0x45, 0xb3,
	0xed, 0x03, 0x28, 0xe7, 0x04, 0x84, 0xdf, 0xa3, 0x2a, 0xec, 0xc0, 0xd0, 0x1b, 0x7a, 0x73, 0xa5,
	0xbb, 0xda, 0x8a, 0xfa, 0xad, 0xe9, 0xc8, 0xed, 0xcd, 0xd3, 0x8c, 0x68, 0xd2, 0x1d, 0x4c, 0x66,
	0xdd, 0x4f, 0xc6, 0x8f, 0xb5, 0xbd, 0x02, 0x5b, 0x2f, 0xd0, 0xb2, 0xf4, 0xf8, 0xe8, 0x8c, 0xf0,
	0x13, 0xa4, 0x7b, 0xce, 0x48, 0x55, 0x7b, 0x33, 0xcf, 0x88, 0x14, 0x4b, 0x69, 0x25, 0xb0, 0xce,
	0x34, 0xb4, 0xbc, 0x43, 0x85, 0x6b, 0xa7, 0x43, 0xdc, 0x42, 0x4b, 0xe1, 0x70, 0x28, 0x58, 0xa2,
	0xbc, 0xee, 0xe4, 0x19, 0x51, 0xa4, 0xe4, 0xa8, 0x98, 0x4c, 0xe1, 0x33, 0x0e, 0xbd, 0xa9, 0x14,
	0x3e, 0xe3, 0xe5, 0x14, 0x3e, 0xe3, 0x72, 0x08, 0x1e, 0x77, 0xd8, 0x08, 0x96, 0xaa, 0xab, 0xc1,
	0x4b, 0x30, 0x37, 0x78, 0x89, 0x60, 0xa1, 0x69, 0xd0, 0x81, 0x85, 0xae, 0xa9, 0x85, 0xa6, 0x41,
	0x67, 0x6e, 0xa1, 0x69, 0xd0, 0x51, 0x96, 0x5d, 0x58, 0xe7, 0xea, 0x85, 0x65, 0xf7, 0x8a, 0x65,
	0xd7, 0xfa, 0xbd, 0x80, 0x6a, 0xb2, 0xc7, 0x1d, 0x46, 0x1d, 0xbc, 0x8d, 0xd6, 0x07, 0x2e, 0x1b,
	0x1c, 0xf6, 0x44, 0x1a, 0xf4, 0x06, 0x61, 0xca, 0xa7, 0xdd, 0x6e, 0xe6, 0x19, 0x59, 0x03, 0xd5,
	0x7e, 0x1a, 0x6c, 0x49, 0x45, 0x29, 0x54, 0x59, 0x85, 0xdf, 0xa2, 0xd5, 0xbe, 0x1f, 0x0e, 0x0e,
	0x7b, 0x3e, 0xe3, 0x07, 0xea, 0xbe, 0x75, 0xfb, 0x41, 0x9e, 0x91, 0x15, 0xe0, 0xbb, 0x80, 0x4b,
	0x11, 0x66, 0x15, 0x78, 0x07, 0x6d, 0x5c, 0x96, 0xa1, 0x62, 0x14, 0xf3, 0x31, 0xf3, 0x8c, 0xdc,
	0x98, 0x26, 0xbb, 0x26, 0xcc, 0x9c, 0x0e, 0x7f, 0x42, 0x1b, 0x31, 0x0b, 0xa8, 0x1c, 0x5f, 0x3c,
	0x8d, 0x54, 0x3c, 0x07, 0x92, 0x67, 0x64, 0xfd, 0x42, 0x77, 0x4d, 0xa8, 0x79, 0x25, 0x7e, 0x87,
	0xaa, 0x2e, 0x15, 0xae, 0x30, 0xaa, 0x70, 0x82, 0x2b, 0xf2, 0x04, 0xd5, 0x75, 0x5c, 0x5e, 0x20,
	0x58, 0x5c, 0xbd, 0x40, 0xc0, 0xd6, 0x0f, 0x0d, 0xd5, 0xe5, 0x09, 0x6e, 0xb9, 0x29, 0x3f, 0xc4,
	0x6f, 0xd0, 0xa2, 0xc4, 0x30, 0xe1, 0xb9, 0x70, 0x0f, 0x55, 0x38, 0x30, 0xb8, 0x12, 0x0d, 0xa8,
	0x5c, 0xb1, 0x43, 0x13, 0x0a, 0xc3, 0x55, 0x2b, 0x96, 0x72, 0x79, 0xc5, 0x92, 0xcc, 0xbc, 0x6e,
	0xfd, 0xff, 0xaf, 0xdb, 0xfe, 0x3c, 0x3e, 0x33, 0x2b, 0xa7, 0xe7, 0xa6, 0x36, 0x3e, 0x37, 0xb5,
	0xef, 0x13, 0xb3, 0x72, 0x32, 0x31, 0xb5, 0xf1, 0xc4, 0xac, 0xfc, 0x9a, 0x98, 0x95, 0xaf, 0x9d,
	0x03, 0x2f, 0x71, 0xd3, 0x7e, 0x6b, 0x10, 0x06, 0x6d, 0x91, 0x46, 0x2c, 0x3e, 0x72, 0x8f, 0x45,
	0x3b, 0x66, 0x41, 0x98, 0xb0, 0x2f, 0xed, 0xeb, 0xfe, 0x9d, 0xfd, 0x25, 0xf8, 0x49, 0xbe, 0xfc,
	0x17, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x90, 0xd3, 0x9c, 0x5a, 0x05, 0x00, 0x00,
}

func (m *FileBase) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FileBase) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FileBase) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsEnd {
		i--
		if m.IsEnd {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Size != 0 {
		i = encodeVarintFilesync(dAtA, i, uint64(m.Size))
		i--
		dAtA[i] = 0x20
	}
	if m.Regular {
		i--
		if m.Regular {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Wpath) > 0 {
		i -= len(m.Wpath)
		copy(dAtA[i:], m.Wpath)
		i = encodeVarintFilesync(dAtA, i, uint64(len(m.Wpath)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintFilesync(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FileList) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FileList) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FileList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Files) > 0 {
		for iNdEx := len(m.Files) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Files[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFilesync(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Strip) > 0 {
		i -= len(m.Strip)
		copy(dAtA[i:], m.Strip)
		i = encodeVarintFilesync(dAtA, i, uint64(len(m.Strip)))
		i--
		dAtA[i] = 0x12
	}
	if m.TotalSize != 0 {
		i = encodeVarintFilesync(dAtA, i, uint64(m.TotalSize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FileIdx) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FileIdx) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FileIdx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Idx != 0 {
		i = encodeVarintFilesync(dAtA, i, uint64(m.Idx))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HashBuf) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HashBuf) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HashBuf) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sum2) > 0 {
		i -= len(m.Sum2)
		copy(dAtA[i:], m.Sum2)
		i = encodeVarintFilesync(dAtA, i, uint64(len(m.Sum2)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Sum1 != 0 {
		i = encodeVarintFilesync(dAtA, i, uint64(m.Sum1))
		i--
		dAtA[i] = 0x20
	}
	if m.Index != 0 {
		i = encodeVarintFilesync(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x18
	}
	if m.Len != 0 {
		i = encodeVarintFilesync(dAtA, i, uint64(m.Len))
		i--
		dAtA[i] = 0x10
	}
	if m.Offset != 0 {
		i = encodeVarintFilesync(dAtA, i, uint64(m.Offset))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HashHead) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HashHead) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HashHead) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hashs) > 0 {
		for iNdEx := len(m.Hashs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Hashs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFilesync(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.RemainderLength != 0 {
		i = encodeVarintFilesync(dAtA, i, uint64(m.RemainderLength))
		i--
		dAtA[i] = 0x20
	}
	if m.CheckSumLength != 0 {
		i = encodeVarintFilesync(dAtA, i, uint64(m.CheckSumLength))
		i--
		dAtA[i] = 0x18
	}
	if m.BlockLength != 0 {
		i = encodeVarintFilesync(dAtA, i, uint64(m.BlockLength))
		i--
		dAtA[i] = 0x10
	}
	if m.CheckSumCount != 0 {
		i = encodeVarintFilesync(dAtA, i, uint64(m.CheckSumCount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FileChunk) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FileChunk) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FileChunk) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsEnd {
		i--
		if m.IsEnd {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintFilesync(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if m.Hash != nil {
		{
			size, err := m.Hash.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFilesync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFilesync(dAtA []byte, offset int, v uint64) int {
	offset -= sovFilesync(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FileBase) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovFilesync(uint64(l))
	}
	l = len(m.Wpath)
	if l > 0 {
		n += 1 + l + sovFilesync(uint64(l))
	}
	if m.Regular {
		n += 2
	}
	if m.Size != 0 {
		n += 1 + sovFilesync(uint64(m.Size))
	}
	if m.IsEnd {
		n += 2
	}
	return n
}

func (m *FileList) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalSize != 0 {
		n += 1 + sovFilesync(uint64(m.TotalSize))
	}
	l = len(m.Strip)
	if l > 0 {
		n += 1 + l + sovFilesync(uint64(l))
	}
	if len(m.Files) > 0 {
		for _, e := range m.Files {
			l = e.ProtoSize()
			n += 1 + l + sovFilesync(uint64(l))
		}
	}
	return n
}

func (m *FileIdx) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Idx != 0 {
		n += 1 + sovFilesync(uint64(m.Idx))
	}
	return n
}

func (m *HashBuf) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Offset != 0 {
		n += 1 + sovFilesync(uint64(m.Offset))
	}
	if m.Len != 0 {
		n += 1 + sovFilesync(uint64(m.Len))
	}
	if m.Index != 0 {
		n += 1 + sovFilesync(uint64(m.Index))
	}
	if m.Sum1 != 0 {
		n += 1 + sovFilesync(uint64(m.Sum1))
	}
	l = len(m.Sum2)
	if l > 0 {
		n += 1 + l + sovFilesync(uint64(l))
	}
	return n
}

func (m *HashHead) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CheckSumCount != 0 {
		n += 1 + sovFilesync(uint64(m.CheckSumCount))
	}
	if m.BlockLength != 0 {
		n += 1 + sovFilesync(uint64(m.BlockLength))
	}
	if m.CheckSumLength != 0 {
		n += 1 + sovFilesync(uint64(m.CheckSumLength))
	}
	if m.RemainderLength != 0 {
		n += 1 + sovFilesync(uint64(m.RemainderLength))
	}
	if len(m.Hashs) > 0 {
		for _, e := range m.Hashs {
			l = e.ProtoSize()
			n += 1 + l + sovFilesync(uint64(l))
		}
	}
	return n
}

func (m *FileChunk) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Hash != nil {
		l = m.Hash.ProtoSize()
		n += 1 + l + sovFilesync(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovFilesync(uint64(l))
	}
	if m.IsEnd {
		n += 2
	}
	return n
}

func sovFilesync(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFilesync(x uint64) (n int) {
	return sovFilesync(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FileBase) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFilesync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FileBase: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FileBase: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFilesync
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFilesync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wpath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFilesync
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFilesync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Wpath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Regular", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Regular = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size", wireType)
			}
			m.Size = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsEnd", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsEnd = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipFilesync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFilesync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FileList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFilesync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FileList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FileList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSize", wireType)
			}
			m.TotalSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Strip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFilesync
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFilesync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Strip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Files", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFilesync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFilesync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Files = append(m.Files, &FileBase{})
			if err := m.Files[len(m.Files)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFilesync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFilesync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FileIdx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFilesync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FileIdx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FileIdx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Idx", wireType)
			}
			m.Idx = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Idx |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFilesync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFilesync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HashBuf) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFilesync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HashBuf: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HashBuf: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Len", wireType)
			}
			m.Len = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Len |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sum1", wireType)
			}
			m.Sum1 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sum1 |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sum2", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFilesync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFilesync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sum2 = append(m.Sum2[:0], dAtA[iNdEx:postIndex]...)
			if m.Sum2 == nil {
				m.Sum2 = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFilesync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFilesync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HashHead) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFilesync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HashHead: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HashHead: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CheckSumCount", wireType)
			}
			m.CheckSumCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CheckSumCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockLength", wireType)
			}
			m.BlockLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockLength |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CheckSumLength", wireType)
			}
			m.CheckSumLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CheckSumLength |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainderLength", wireType)
			}
			m.RemainderLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainderLength |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hashs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFilesync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFilesync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hashs = append(m.Hashs, &HashBuf{})
			if err := m.Hashs[len(m.Hashs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFilesync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFilesync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FileChunk) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFilesync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FileChunk: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FileChunk: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFilesync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFilesync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Hash == nil {
				m.Hash = &HashBuf{}
			}
			if err := m.Hash.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFilesync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFilesync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsEnd", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsEnd = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipFilesync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFilesync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFilesync(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFilesync
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFilesync
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFilesync
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFilesync
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFilesync
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFilesync        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFilesync          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFilesync = fmt.Errorf("proto: unexpected end of group")
)
